name: firestore_migration
description: A Dart console application for firestore migration.
version: 1.0.0
homepage: https://github.com/swimmingkiim/firestore_migration

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1
  dart_console: ^1.1.2
  firebaseapis: ^0.1.2
  version: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
